// app/frontend/src/pages/About.jsx
//
// Static page that explains the scope of the cloud-care project. The web app
// itself is intentionally minimal — the value of this repo lives in the AWS
// infrastructure code under terraform/ and the GitHub Actions pipelines.

const phases = [
  {
    n: "00",
    title: "State backend",
    body: "S3 bucket for Terraform state + DynamoDB table for state locking. Bootstrapped with local state, then everything else uses the remote backend.",
  },
  {
    n: "01",
    title: "Networking",
    body: "VPC across two AZs with public, app, and database subnets. Internet Gateway, NAT instance, route tables, security groups (stateful), and NACLs (stateless).",
  },
  {
    n: "02",
    title: "Compute",
    body: "EC2 fleet managed by a Launch Template + Auto Scaling Group, fronted by an Application Load Balancer. IAM role + instance profile, ECR repository, instance refresh rollouts.",
  },
  {
    n: "03",
    title: "Database",
    body: "RDS PostgreSQL in private subnets, master credentials generated by Terraform and stored in AWS Secrets Manager. Backend pulls them at runtime via IAM.",
  },
  {
    n: "04",
    title: "Application",
    body: "FastAPI backend in a Docker image (pushed to ECR), React + Vite frontend bundle. The web UI is deliberately basic — it exists to exercise the infrastructure.",
  },
  {
    n: "05",
    title: "Content delivery",
    body: "Static frontend assets in S3, served through CloudFront with Origin Access Control. API traffic is routed by a CloudFront behavior to the ALB origin. SPA fallback configured.",
  },
  {
    n: "06",
    title: "Serverless",
    body: "Two Lambda functions behind API Gateway HTTP APIs: an audit log writer backed by DynamoDB, and a contact form handler that sends email via SES.",
  },
  {
    n: "07",
    title: "Observability & cost",
    body: "CloudWatch metrics, log groups, dashboards, and alarms across ALB, RDS, Lambda, and DynamoDB. SNS topic + email subscription for alerts. AWS Budgets for cost guardrails.",
  },
  {
    n: "08",
    title: "CI/CD",
    body: "GitHub Actions OIDC federation to AWS (no long-lived keys). Separate workflows for Terraform plan/apply, backend image build + ASG refresh, and frontend build + S3 sync + CloudFront invalidation.",
  },
];

const stack = [
  "AWS",
  "Terraform 1.9",
  "S3 + DynamoDB (state)",
  "VPC / Subnets / NACLs / SGs",
  "EC2 / ASG / ALB",
  "ECR",
  "RDS PostgreSQL",
  "Secrets Manager",
  "Lambda",
  "API Gateway",
  "DynamoDB",
  "SES",
  "CloudFront",
  "S3 (static hosting)",
  "CloudWatch",
  "SNS",
  "IAM + OIDC",
  "GitHub Actions",
  "Docker",
  "FastAPI",
  "React + Vite",
];

const practices = [
  "Remote state with locking to make Terraform safe for teams",
  "Per-stack state isolation; cross-stack reads via terraform_remote_state",
  "Least-privilege IAM (resource-scoped policies, condition keys on SES)",
  "Multi-AZ networking and private subnets for app and DB tiers",
  "Immutable image deploys via ECR + ASG instance refresh",
  "Static assets through CloudFront with cache invalidation on deploy",
  "Workflow concurrency to prevent state-lock and refresh races",
  "Observability across three pillars: metrics, logs, alarms",
  "Cost controls via Budgets and free-tier-aware sizing",
  "Keyless GitHub Actions auth via OIDC federation",
];

export default function About() {
  return (
    <>
      <section className="card hero">
        <div className="card-body">
          <span className="eyebrow">About the project</span>
          <h2 className="hero-title">CloudCare HMS — an AWS DevOps showcase</h2>
          <p className="hero-lead">
            CloudCare is a small hospital management application used as a
            vehicle to build, operate, and document a real production-style
            AWS environment with Terraform and GitHub Actions. The interesting
            work happens under <code>terraform/</code> and{" "}
            <code>.github/workflows/</code>, not in this web UI.
          </p>
        </div>
      </section>

      <section className="card scope">
        <div className="card-body">
          <h3 className="section-heading">Scope &mdash; what this repo is not</h3>
          <p>
            This project is intentionally focused on the <strong>DevOps and SRE
            side</strong>: infrastructure-as-code, networking, IAM, deployment
            pipelines, observability, and cost control. The application logic
            (patients, appointments) is the simplest possible CRUD that gives the
            infrastructure something to host.
          </p>
          <p className="muted">
            <strong>UI/UX is out of scope.</strong> The web frontend exists to
            prove the stack is wired up end-to-end (CloudFront &rarr; S3 for
            assets, CloudFront &rarr; ALB &rarr; EC2 &rarr; RDS for the API). It
            is not designed as a product, and visual polish was not a goal.
          </p>
        </div>
      </section>

      <section className="card">
        <div className="card-header">
          <h3 className="card-title">Roadmap &mdash; 8 phases</h3>
          <span className="card-count">{phases.length} phases</span>
        </div>
        <div className="card-body">
          <ol className="phase-list">
            {phases.map((p) => (
              <li key={p.n} className="phase-item">
                <span className="phase-number">{p.n}</span>
                <div className="phase-body">
                  <h4 className="phase-title">{p.title}</h4>
                  <p className="phase-desc">{p.body}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section className="card">
        <div className="card-header">
          <h3 className="card-title">Engineering practices demonstrated</h3>
        </div>
        <div className="card-body">
          <ul className="practice-list">
            {practices.map((p) => (
              <li key={p} className="practice-item">
                <span className="check" aria-hidden="true">&#10003;</span>
                <span>{p}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="card">
        <div className="card-header">
          <h3 className="card-title">Tech stack</h3>
          <span className="card-count">{stack.length} tools</span>
        </div>
        <div className="card-body">
          <div className="chip-cloud">
            {stack.map((s) => (
              <span key={s} className="tech-chip">{s}</span>
            ))}
          </div>
        </div>
      </section>

      <section className="card">
        <div className="card-body">
          <h3 className="section-heading">Architecture at a glance</h3>
          <p>
            Users hit <strong>CloudFront</strong>. Static React assets come from
            an <strong>S3</strong> bucket via Origin Access Control. API requests
            (<code>/api/*</code>) are forwarded to an{" "}
            <strong>Application Load Balancer</strong>, which routes to an{" "}
            <strong>Auto Scaling Group</strong> of EC2 instances running the
            FastAPI backend container pulled from <strong>ECR</strong>. The
            backend talks to a private <strong>RDS PostgreSQL</strong> instance
            using credentials fetched from <strong>Secrets Manager</strong>.
          </p>
          <p>
            Side flows run on serverless: a contact form posts to{" "}
            <strong>API Gateway &rarr; Lambda &rarr; SES</strong>, and audit
            events go to <strong>API Gateway &rarr; Lambda &rarr; DynamoDB</strong>.{" "}
            <strong>CloudWatch</strong> collects metrics and logs across every
            tier, with alarms fanning out through <strong>SNS</strong> to email.
          </p>
        </div>
      </section>

      <footer className="page-footer">
        <p>
          Built by chala2001 as an AWS/Terraform learning project. Source on{" "}
          <a href="https://github.com/chala2001/cloud-care" target="_blank" rel="noreferrer">
            GitHub
          </a>
          .
        </p>
      </footer>
    </>
  );
}
